# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26549cac4636165ad656f8fe4adab5205fc91d6f94057f6a383fb0d3f5a13073f9f414f94939dc1078a61323f769951dbd85e4b73285f99be4413dae1cc6b1c3

test:
  secret_key_base: a539f6af605d1e5fdb99fdbba83e70043d88f42f482c1f291de7bc5b7f266acc59ec4acf27c3dd5c08066bfdb416dc0cdc722fbeb5b2e4b3f7d455623bf63360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
